apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ctfd
  namespace: security-champion-admin
  labels:
    team: security-champion-admin
spec:
  image: ctfd/ctfd:3.5.0
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: ctfd
          - envVarPrefix: DATABASE

  env:
    - UPLOAD_FOLDER=/var/uploads
    - WORKERS=1
    - LOG_FOLDER=/var/log/CTFd
    - ACCESS_LOG=-
    - ERROR_LOG=-
    - REVERSE_PROXY=true