apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ctfd
  namespace: security-champion-admin
  labels:
    team: security-champion-admin
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://ctfd.intern.dev.nav.no
  liveness:
    path: /
  readiness:
    path: /challenges
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - envVarPrefix: DATABASE
            name: ctfd
  env:
  - name: UPLOAD_FOLDER
    value: /var/uploads
  - name: WORKERS
    value: "1"
  - name: LOG_FOLDER
    value: /var/log/CTFd
  - name: ACCESS_LOG
    value: "-"
  - name: ERROR_LOG
    value: "-"
  - name: REVERSE_PROXY
    value: "true"
  - name: REDIS_URL
    value: redis-ctf.security-champions-admin.svc.cluster.local
  accessPolicy:
    outbound:
      rules:
        - application: ctfd-redis