apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ctfd
  namespace: security-champion-admin
  labels:
    team: security-champion-admin
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://ctfd.dev.intern.nav.no
  liveness:
    path: /
  readiness:
    path: /challenges
  replicas:
    min: 1
    max: 1
#  gcp:
#    sqlInstances:
#      - type: POSTGRES_14
#        databases:
#          - envVarPrefix: DATABASE
#            name: ctfd
  env:
    - name: UPLOAD_FOLDER
      value: /tmp/uploads
    - name: WORKERS
      value: "1"
    - name: LOG_FOLDER
      value: /tmp/log/CTFd
    - name: ACCESS_LOG
      value: "-"
    - name: ERROR_LOG
      value: "-"
    - name: REVERSE_PROXY
      value: "true"
    - name: REDIS_URL
      value: redis://redis-ctf.security-champions-admin.svc.cluster.local
    - name: DATABASE_URL
      value: sqlite:////tmp/ctfd.db
  accessPolicy:
    outbound:
      rules:
        - application: ctfd-redis